$(document).ready(function() {
  // Predefined list of majors
  var commonMajors = [
    "Computer Science",
    "Business Administration",
    "Psychology",
    "Nursing",
    "Biology",
    "Communications",
    "Political Science",
    "Marketing",
    "English",
    "Finance",
    "Accounting",
    "Economics",
    "Education",
    "Chemistry",
    "History",
    "Sociology",
    "Art",
    "Physics",
    "Mathematics",
    "Engineering",
    "Graphic Design",
    "International Relations",
    "Health Sciences",
    "Criminal Justice",
    "Music",
    "Film Studies",
    "Environmental Science",
    "Philosophy",
    "Theater",
    "Anthropology",
    "Public Health",
    "Architecture",
    "Journalism",
    "Social Work",
    "Information Technology",
    "Human Resources",
    "Hospitality Management",
    "Nutrition",
    "Fine Arts",
    "Sports Management",
    "Biochemistry",
    "Geology",
    "Astronomy",
    "Linguistics",
    "Dance",
    "Religious Studies",
    "Interior Design",
    "Fashion Design",
    "Forensic Science",
    "Women's Studies",
    "Urban Planning",
    "Public Relations",
    "Theology",
    "Industrial Design",
    "Biomedical Engineering",
    "Microbiology",
    "Computer Engineering",
    "Kinesiology",
    "Medical Technology",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Materials Science",
    "Marine Biology",
    "Actuarial Science",
    "Neuroscience",
    "Robotics",
    "Biotechnology",
    "Civil Engineering",
    "Industrial Engineering",
    "Healthcare Administration",
    "Behavioral Science",
    "Applied Mathematics",
    "Medical Imaging",
    "Gerontology",
    "Environmental Engineering",
    "Genetics",
    "Biophysics",
    "Cognitive Science",
    "Quantum Physics",
    "Counseling Psychology",
    "Sports Medicine",
    "Political Philosophy",
    "Software Engineering",
    "Paleontology",
    "Humanities",
    "Renewable Energy",
    "Photography",
    "Astrophysics",
    "Business Analytics",
    "International Business",
    "Data Science",
    "Cybersecurity",
    "Geography",
    "Geophysics",
    "Data Analytics",
    "Archeology",
    "Petroleum Engineering",
    "Hospitality and Tourism Management"
  ];

  // Initialize Selectize
  $('#majorInput').selectize({
    plugins: ['remove_button'],
    delimiter: ',',
    persist: false,
    create: true,
    createOnBlur: true,
    dropdownParent: 'body',
    placeholder: 'Search for your major',
    closeAfterSelect: true,
    options: commonMajors.map(function(major) {
      return { value: major, text: major };
    }),
    onChange: function(value) {
      // Assign value to the profile or perform any other necessary action
    }
  });
});
